<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data =[
            [
                'title_en'=>'Terms Of Service',
                'title_ja'=>'利用規約',
                'type'=>'terms_of_service',
                'description_en'=>'', 
                'description_ja'=> '\n\nThis Privacy Policy describes how Our Works ("we," "our," or "us") collects, uses, and shares the personal information of users ("you" or "your") of our website. By using our Website, you consent to the practices described in this Privacy Policy.\n\n1.Information We Collect\n\nWe may collect various types of information, including:\n\nPersonal Information: This includes information that can identify you, such as your name, email address, phone number, or postal address, which you may provide when contacting us or filling out forms on our Website.\n\nUsage Information: We collect information about your interactions with our Website, such as your IP address, browser type, referring/exit pages, and operating system.\n\n2.Cookies:\n\nWe use cookies and similar tracking technologies to gather information about your browsing activities on our Website. You can control cookies through your browser settings, but please note that disabling cookies may affect your experience on our Website.\n\n3.How We Use Your Information\n\nWe use the collected information for various purposes, including:\n\nProviding Services: To provide you with the services and information you request from us.\n\nImproving Our Website: To enhance and personalize your experience on our Website and to analyze user preferences and trends.\n\nCommunications: To communicate with you, respond to your inquiries, and provide updates on our services.\n\nLegal Compliance: To comply with applicable laws, regulations, and legal processes.\n\n4.Sharing Your Information\n\nWe do not sell, trade, or rent your personal information to third parties. However, we may share your information with:\n\nService Providers: We may share your information with third-party service providers who assist us in operating our Website or providing our services.\n\nLegal Requirements: We may disclose your information in response to a legal request, court order, or government investigation.\n\n5.Security\n\nWe take reasonable steps to protect your personal information from unauthorized access, disclosure, alteration, or destruction. However, please be aware that no method of transmitting information over the internet is completely secure, and we cannot guarantee the security of your data.\n\nYour Choices\n\nYou have the right to:\n\nAccess, correct, or delete your personal information.\n\nOpt out of receiving marketing communications from us.\n\nDisable cookies through your browser settings.\n\n6.Changes to this Privacy Policy\n\nWe may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. The updated policy will be posted on our Website with the date of the latest revision.\n\n7.Contact Us\n\nIf you have any questions or concerns about this Privacy Policy or our data practices, please contact us at: \n\n',],
           
             [
                'title_en'=>'User Policy',
                 'title_ja'=>'User Policy',
                'type'=>'user_policy'
                ,'description'=> '\n\nThis Privacy Policy describes how Our Works ("we," "our," or "us") collects, uses, and shares the personal information of users ("you" or "your") of our website. By using our Website, you consent to the practices described in this Privacy Policy.\n\n1.Information We Collect\n\nWe may collect various types of information, including:\n\nPersonal Information: This includes information that can identify you, such as your name, email address, phone number, or postal address, which you may provide when contacting us or filling out forms on our Website.\n\nUsage Information: We collect information about your interactions with our Website, such as your IP address, browser type, referring/exit pages, and operating system.\n\n2.Cookies:\n\nWe use cookies and similar tracking technologies to gather information about your browsing activities on our Website. You can control cookies through your browser settings, but please note that disabling cookies may affect your experience on our Website.\n\n3.How We Use Your Information\n\nWe use the collected information for various purposes, including:\n\nProviding Services: To provide you with the services and information you request from us.\n\nImproving Our Website: To enhance and personalize your experience on our Website and to analyze user preferences and trends.\n\nCommunications: To communicate with you, respond to your inquiries, and provide updates on our services.\n\nLegal Compliance: To comply with applicable laws, regulations, and legal processes.\n\n4.Sharing Your Information\n\nWe do not sell, trade, or rent your personal information to third parties. However, we may share your information with:\n\nService Providers: We may share your information with third-party service providers who assist us in operating our Website or providing our services.\n\nLegal Requirements: We may disclose your information in response to a legal request, court order, or government investigation.\n\n5.Security\n\nWe take reasonable steps to protect your personal information from unauthorized access, disclosure, alteration, or destruction. However, please be aware that no method of transmitting information over the internet is completely secure, and we cannot guarantee the security of your data.\n\nYour Choices\n\nYou have the right to:\n\nAccess, correct, or delete your personal information.\n\nOpt out of receiving marketing communications from us.\n\nDisable cookies through your browser settings.\n\n6.Changes to this Privacy Policy\n\nWe may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. The updated policy will be posted on our Website with the date of the latest revision.\n\n7.Contact Us\n\nIf you have any questions or concerns about this Privacy Policy or our data practices, please contact us at: \n\n',],
            [
                'title_en'=>'Privacy Policy',
                 'title_ja'=>'User Policy',
                'type'=>'privacy_policy'
                ,'description'=> '\n\nThis Privacy Policy describes how Our Works ("we," "our," or "us") collects, uses, and shares the personal information of users ("you" or "your") of our website. By using our Website, you consent to the practices described in this Privacy Policy.\n\n1.Information We Collect\n\nWe may collect various types of information, including:\n\nPersonal Information: This includes information that can identify you, such as your name, email address, phone number, or postal address, which you may provide when contacting us or filling out forms on our Website.\n\nUsage Information: We collect information about your interactions with our Website, such as your IP address, browser type, referring/exit pages, and operating system.\n\n2.Cookies:\n\nWe use cookies and similar tracking technologies to gather information about your browsing activities on our Website. You can control cookies through your browser settings, but please note that disabling cookies may affect your experience on our Website.\n\n3.How We Use Your Information\n\nWe use the collected information for various purposes, including:\n\nProviding Services: To provide you with the services and information you request from us.\n\nImproving Our Website: To enhance and personalize your experience on our Website and to analyze user preferences and trends.\n\nCommunications: To communicate with you, respond to your inquiries, and provide updates on our services.\n\nLegal Compliance: To comply with applicable laws, regulations, and legal processes.\n\n4.Sharing Your Information\n\nWe do not sell, trade, or rent your personal information to third parties. However, we may share your information with:\n\nService Providers: We may share your information with third-party service providers who assist us in operating our Website or providing our services.\n\nLegal Requirements: We may disclose your information in response to a legal request, court order, or government investigation.\n\n5.Security\n\nWe take reasonable steps to protect your personal information from unauthorized access, disclosure, alteration, or destruction. However, please be aware that no method of transmitting information over the internet is completely secure, and we cannot guarantee the security of your data.\n\nYour Choices\n\nYou have the right to:\n\nAccess, correct, or delete your personal information.\n\nOpt out of receiving marketing communications from us.\n\nDisable cookies through your browser settings.\n\n6.Changes to this Privacy Policy\n\nWe may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. The updated policy will be posted on our Website with the date of the latest revision.\n\n7.Contact Us\n\nIf you have any questions or concerns about this Privacy Policy or our data practices, please contact us at: \n\n',],
            [
                'title_en'=>'Terms Of Service Company',
                 'title_ja'=>'User Policy',
                'type'=>'terms_of_service_company'
                ,'description'=> '\n\nThis Privacy Policy describes how Our Works ("we," "our," or "us") collects, uses, and shares the personal information of users ("you" or "your") of our website. By using our Website, you consent to the practices described in this Privacy Policy.\n\n1.Information We Collect\n\nWe may collect various types of information, including:\n\nPersonal Information: This includes information that can identify you, such as your name, email address, phone number, or postal address, which you may provide when contacting us or filling out forms on our Website.\n\nUsage Information: We collect information about your interactions with our Website, such as your IP address, browser type, referring/exit pages, and operating system.\n\n2.Cookies:\n\nWe use cookies and similar tracking technologies to gather information about your browsing activities on our Website. You can control cookies through your browser settings, but please note that disabling cookies may affect your experience on our Website.\n\n3.How We Use Your Information\n\nWe use the collected information for various purposes, including:\n\nProviding Services: To provide you with the services and information you request from us.\n\nImproving Our Website: To enhance and personalize your experience on our Website and to analyze user preferences and trends.\n\nCommunications: To communicate with you, respond to your inquiries, and provide updates on our services.\n\nLegal Compliance: To comply with applicable laws, regulations, and legal processes.\n\n4.Sharing Your Information\n\nWe do not sell, trade, or rent your personal information to third parties. However, we may share your information with:\n\nService Providers: We may share your information with third-party service providers who assist us in operating our Website or providing our services.\n\nLegal Requirements: We may disclose your information in response to a legal request, court order, or government investigation.\n\n5.Security\n\nWe take reasonable steps to protect your personal information from unauthorized access, disclosure, alteration, or destruction. However, please be aware that no method of transmitting information over the internet is completely secure, and we cannot guarantee the security of your data.\n\nYour Choices\n\nYou have the right to:\n\nAccess, correct, or delete your personal information.\n\nOpt out of receiving marketing communications from us.\n\nDisable cookies through your browser settings.\n\n6.Changes to this Privacy Policy\n\nWe may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. The updated policy will be posted on our Website with the date of the latest revision.\n\n7.Contact Us\n\nIf you have any questions or concerns about this Privacy Policy or our data practices, please contact us at: \n\n',],
            [
                'title_en'=>'Job Policy ',
                 'title_ja'=>'User Policy',
                'type'=>'job_policy'
                ,'description'=> '\n\nThis Privacy Policy describes how Our Works ("we," "our," or "us") collects, uses, and shares the personal information of users ("you" or "your") of our website. By using our Website, you consent to the practices described in this Privacy Policy.\n\n1.Information We Collect\n\nWe may collect various types of information, including:\n\nPersonal Information: This includes information that can identify you, such as your name, email address, phone number, or postal address, which you may provide when contacting us or filling out forms on our Website.\n\nUsage Information: We collect information about your interactions with our Website, such as your IP address, browser type, referring/exit pages, and operating system.\n\n2.Cookies:\n\nWe use cookies and similar tracking technologies to gather information about your browsing activities on our Website. You can control cookies through your browser settings, but please note that disabling cookies may affect your experience on our Website.\n\n3.How We Use Your Information\n\nWe use the collected information for various purposes, including:\n\nProviding Services: To provide you with the services and information you request from us.\n\nImproving Our Website: To enhance and personalize your experience on our Website and to analyze user preferences and trends.\n\nCommunications: To communicate with you, respond to your inquiries, and provide updates on our services.\n\nLegal Compliance: To comply with applicable laws, regulations, and legal processes.\n\n4.Sharing Your Information\n\nWe do not sell, trade, or rent your personal information to third parties. However, we may share your information with:\n\nService Providers: We may share your information with third-party service providers who assist us in operating our Website or providing our services.\n\nLegal Requirements: We may disclose your information in response to a legal request, court order, or government investigation.\n\n5.Security\n\nWe take reasonable steps to protect your personal information from unauthorized access, disclosure, alteration, or destruction. However, please be aware that no method of transmitting information over the internet is completely secure, and we cannot guarantee the security of your data.\n\nYour Choices\n\nYou have the right to:\n\nAccess, correct, or delete your personal information.\n\nOpt out of receiving marketing communications from us.\n\nDisable cookies through your browser settings.\n\n6.Changes to this Privacy Policy\n\nWe may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. The updated policy will be posted on our Website with the date of the latest revision.\n\n7.Contact Us\n\nIf you have any questions or concerns about this Privacy Policy or our data practices, please contact us at: \n\n',],
            [
                'title_en'=>'Terms Of Service',
                 'title_ja'=>'User Policy',
                'type'=>'terms_of_service'
                ,'description'=> 'このプライバシー ポリシーでは、[貴社名] (「当社」、「当社」、または「当社」) が当社 Web サイトのユーザー (「あなた」、または「あなたの」) の個人情報をどのように収集、使用、および共有するかについて説明します。ウェブサイト URL] (「ウェブサイト」)。当社の Web サイトを使用することにより、このプライバシー ポリシーに記載されている慣行に同意したことになります。\n\n1.当社が収集する情報\n\n当社は、次のようなさまざまな種類の情報を収集する場合があります。\n\n個人情報: これには、お客様が当社に連絡するとき、または当社のウェブサイト上のフォームに記入するときに提供する、お客様の名前、電子メール アドレス、電話番号、郵便番号など、お客様を特定できる情報が含まれます。\n\n使用状況情報: 当社は、IP アドレス、ブラウザの種類、ページの参照/終了、オペレーティング システムなど、当社 Web サイトとのやり取りに関する情報を収集します。\n\n2.クッキー:\n\n当社は、Cookie および同様の追跡技術を使用して、当社 Web サイトでの閲覧活動に関する情報を収集します。ブラウザの設定を通じて Cookie を制御できますが、Cookie を無効にすると、当社の Web サイトでのエクスペリエンスに影響を与える可能性があることに注意してください。\n\n3.お客様の情報の使用方法\n\n当社は収集した情報を次のようなさまざまな目的で使用します。\n\nサービスの提供: お客様が当社に要求するサービスおよび情報を提供するため\n\n当社の Web サイトの改善: 当社の Web サイトでのエクスペリエンスを強化およびパーソナライズし、ユーザーの好みや傾向を分析するため。\n\nコミュニケーション: お客様とコミュニケーションし、お問い合わせに回答し、当社のサービスに関する最新情報を提供するため。\n\n法的遵守: 適用される法律、規制、および法的手続きを遵守すること。\n\n4.あなたの情報の共有\n\n当社はお客様の個人情報を第三者に販売、取引、または貸与することはありません。ただし、お客様の情報を次の者と共有する場合があります。\n\nサービスプロバイダー: 当社は、当社のウェブサイトの運営やサービスの提供を支援するサードパーティのサービスプロバイダーとお客様の情報を共有する場合があります。\n\n法的要件: 当社は、法的要求、裁判所命令、または政府の調査に応じてお客様の情報を開示する場合があります。\n\n5.セキュリティ\n\n当社は、お客様の個人情報を不正なアクセス、開示、変更、または破壊から保護するために合理的な措置を講じます。ただし、インターネット上で情報を送信する方法は完全に安全ではなく、当社はデータの安全性を保証できないことにご注意ください。\n\nあなたの選択\n\nあなたには次の権利があります。\n\n自分の個人情報にアクセスし、修正または削除します。\n\n当社からのマーケティング情報の受信をオプトアウトします。\n\nブラウザの設定で Cookie を無効にします。\n\n6.本プライバシーポリシーの変更\n\n当社は、当社の慣行の変更を反映するため、またはその他の運用上、法律上、または規制上の理由により、本プライバシー ポリシーを随時更新することがあります。更新されたポリシーは、最新の改訂日とともに当社の Web サイトに掲載されます。\n\n7.お問い合わせ\n\nこのプライバシー ポリシーまたは当社のデータ慣行に関してご質問や懸念がある場合は、以下までお問い合わせください。',],
            [
                'title_en'=>'Privacy Policy',
                 'title_ja'=>'User Policy',
                'type'=>'privacy_policy'
                ,'description'=> ' このプライバシー ポリシーでは、[貴社名] (「当社」、「当社」、または「当社」) が当社 Web サイトのユーザー (「あなた」、または「あなたの」) の個人情報をどのように収集、使用、および共有するかについて説明します。ウェブサイト URL] (「ウェブサイト」)。当社の Web サイトを使用することにより、このプライバシー ポリシーに記載されている慣行に同意したものとみなされます。\n\n1.当社が収集する情報/n/n 当社は、次のようなさまざまな種類の情報を収集する場合があります。\n\n個人情報: これには、お客様が当社に連絡するとき、または当社のウェブサイト上のフォームに記入するときに提供する、お客様の名前、電子メール アドレス、電話番号、郵便番号など、お客様を特定できる情報が含まれます。\n\n使用状況情報: 当社は、IP アドレス、ブラウザの種類、ページの参照/終了、オペレーティング システムなど、当社 Web サイトとのやり取りに関する情報を収集します。\n\n2.クッキー:\n\n当社は、Cookie および同様の追跡技術を使用して、当社 Web サイトでの閲覧活動に関する情報を収集します。ブラウザの設定を通じて Cookie を制御できますが、Cookie を無効にすると、当社の Web サイトでのエクスペリエンスに影響を及ぼす可能性があることに注意してください。\n\n3.お客様の情報の使用方法\n\n当社は収集した情報を次のようなさまざまな目的に使用します。\n\n サービスの提供: お客様が当社に要求するサービスおよび情報を提供するため。\n\n当社の Web サイトの改善: 当社の Web サイトでのエクスペリエンスを強化およびパーソナライズし、ユーザーの好みや傾向を分析するため。\n\nコミュニケーション: お客様とコミュニケーションし、お問い合わせに回答し、当社のサービスに関する最新情報を提供するため。\n\n法的遵守: 適用される法律、規制、および法的手続きを遵守すること。\n\n4.情報の共有\n\n当社はお客様の個人情報を第三者に販売、取引、または貸与することはありません。ただし、お客様の情報を次の者と共有する場合があります。\n\nサービスプロバイダー: 当社は、当社のウェブサイトの運営やサービスの提供を支援するサードパーティのサービスプロバイダーとお客様の情報を共有する場合があります。\n\n法的要件: 当社は、法的要求、裁判所命令、または政府の調査に応じてお客様の情報を開示する場合があります。\n\n5.セキュリティ\n\n 当社は、お客様の個人情報を不正なアクセス、開示、変更、または破壊から保護するために合理的な措置を講じます。ただし、インターネット上で情報を送信する方法は完全に安全ではなく、当社はデータの安全性を保証できないことにご注意ください。\n\nあなたの選択\n\nあなたには次の権利があります。\n\n自分の個人情報にアクセスし、修正または削除します。\n\n 当社からのマーケティング情報の受信をオプトアウトします。\n\nブラウザの設定で Cookie を無効にします。\n\n6.本プライバシーポリシーの変更\n\n当社は、当社の慣行の変更を反映するため、またはその他の運用上、法律上、または規制上の理由により、本プライバシー ポリシーを随時更新することがあります。更新されたポリシーは、最新の改訂日とともに当社の Web サイトに掲載されます。\n\n7.お問い合わせ\n\nこのプライバシー ポリシーまたは当社のデータ慣行に関してご質問や懸念がある場合は、以下までお問い合わせください。',],
            [
                'title_en'=>'User Policy',
                 'title_ja'=>'User Policy',
                'type'=>'user_policy'
                ,'description'=> ' このプライバシー ポリシーでは、[貴社名] (「当社」、「当社」、または「当社」) が当社 Web サイトのユーザー (「あなた」、または「あなたの」) の個人情報をどのように収集、使用、および共有するかについて説明します。ウェブサイト URL] (「ウェブサイト」)。当社の Web サイトを使用することにより、このプライバシー ポリシーに記載されている慣行に同意したものとみなされます。\n\n1.当社が収集する情報/n/n 当社は、次のようなさまざまな種類の情報を収集する場合があります。\n\n個人情報: これには、お客様が当社に連絡するとき、または当社のウェブサイト上のフォームに記入するときに提供する、お客様の名前、電子メール アドレス、電話番号、郵便番号など、お客様を特定できる情報が含まれます。\n\n使用状況情報: 当社は、IP アドレス、ブラウザの種類、ページの参照/終了、オペレーティング システムなど、当社 Web サイトとのやり取りに関する情報を収集します。\n\n2.クッキー:\n\n当社は、Cookie および同様の追跡技術を使用して、当社 Web サイトでの閲覧活動に関する情報を収集します。ブラウザの設定を通じて Cookie を制御できますが、Cookie を無効にすると、当社の Web サイトでのエクスペリエンスに影響を及ぼす可能性があることに注意してください。\n\n3.お客様の情報の使用方法\n\n当社は収集した情報を次のようなさまざまな目的に使用します。\n\n サービスの提供: お客様が当社に要求するサービスおよび情報を提供するため。\n\n当社の Web サイトの改善: 当社の Web サイトでのエクスペリエンスを強化およびパーソナライズし、ユーザーの好みや傾向を分析するため。\n\nコミュニケーション: お客様とコミュニケーションし、お問い合わせに回答し、当社のサービスに関する最新情報を提供するため。\n\n法的遵守: 適用される法律、規制、および法的手続きを遵守すること。\n\n4.情報の共有\n\n当社はお客様の個人情報を第三者に販売、取引、または貸与することはありません。ただし、お客様の情報を次の者と共有する場合があります。\n\nサービスプロバイダー: 当社は、当社のウェブサイトの運営やサービスの提供を支援するサードパーティのサービスプロバイダーとお客様の情報を共有する場合があります。\n\n法的要件: 当社は、法的要求、裁判所命令、または政府の調査に応じてお客様の情報を開示する場合があります。\n\n5.セキュリティ\n\n 当社は、お客様の個人情報を不正なアクセス、開示、変更、または破壊から保護するために合理的な措置を講じます。ただし、インターネット上で情報を送信する方法は完全に安全ではなく、当社はデータの安全性を保証できないことにご注意ください。\n\nあなたの選択\n\nあなたには次の権利があります。\n\n自分の個人情報にアクセスし、修正または削除します。\n\n 当社からのマーケティング情報の受信をオプトアウトします。\n\nブラウザの設定で Cookie を無効にします。\n\n6.本プライバシーポリシーの変更\n\n当社は、当社の慣行の変更を反映するため、またはその他の運用上、法律上、または規制上の理由により、本プライバシー ポリシーを随時更新することがあります。更新されたポリシーは、最新の改訂日とともに当社の Web サイトに掲載されます。\n\n7.お問い合わせ\n\nこのプライバシー ポリシーまたは当社のデータ慣行に関してご質問や懸念がある場合は、以下までお問い合わせください',],
            [
                'title_en'=>'Term Of Service Company',
                 'title_ja'=>'User Policy',
                'type'=>'terms_of_service_company'
                ,'description'=> ' このプライバシー ポリシーでは、[貴社名] (「当社」、「当社」、または「当社」) が当社 Web サイトのユーザー (「あなた」、または「あなたの」) の個人情報をどのように収集、使用、および共有するかについて説明します。ウェブサイト URL] (「ウェブサイト」)。当社の Web サイトを使用することにより、このプライバシー ポリシーに記載されている慣行に同意したものとみなされます。\n\n1.当社が収集する情報/n/n 当社は、次のようなさまざまな種類の情報を収集する場合があります。\n\n個人情報: これには、お客様が当社に連絡するとき、または当社のウェブサイト上のフォームに記入するときに提供する、お客様の名前、電子メール アドレス、電話番号、郵便番号など、お客様を特定できる情報が含まれます。\n\n使用状況情報: 当社は、IP アドレス、ブラウザの種類、ページの参照/終了、オペレーティング システムなど、当社 Web サイトとのやり取りに関する情報を収集します。\n\n2.クッキー:\n\n当社は、Cookie および同様の追跡技術を使用して、当社 Web サイトでの閲覧活動に関する情報を収集します。ブラウザの設定を通じて Cookie を制御できますが、Cookie を無効にすると、当社の Web サイトでのエクスペリエンスに影響を及ぼす可能性があることに注意してください。\n\n3.お客様の情報の使用方法\n\n当社は収集した情報を次のようなさまざまな目的に使用します。\n\n サービスの提供: お客様が当社に要求するサービスおよび情報を提供するため。\n\n当社の Web サイトの改善: 当社の Web サイトでのエクスペリエンスを強化およびパーソナライズし、ユーザーの好みや傾向を分析するため。\n\nコミュニケーション: お客様とコミュニケーションし、お問い合わせに回答し、当社のサービスに関する最新情報を提供するため。\n\n法的遵守: 適用される法律、規制、および法的手続きを遵守すること。\n\n4.情報の共有\n\n当社はお客様の個人情報を第三者に販売、取引、または貸与することはありません。ただし、お客様の情報を次の者と共有する場合があります。\n\nサービスプロバイダー: 当社は、当社のウェブサイトの運営やサービスの提供を支援するサードパーティのサービスプロバイダーとお客様の情報を共有する場合があります。\n\n法的要件: 当社は、法的要求、裁判所命令、または政府の調査に応じてお客様の情報を開示する場合があります。\n\n5.セキュリティ\n\n 当社は、お客様の個人情報を不正なアクセス、開示、変更、または破壊から保護するために合理的な措置を講じます。ただし、インターネット上で情報を送信する方法は完全に安全ではなく、当社はデータの安全性を保証できないことにご注意ください。\n\nあなたの選択\n\nあなたには次の権利があります。\n\n自分の個人情報にアクセスし、修正または削除します。\n\n 当社からのマーケティング情報の受信をオプトアウトします。\n\nブラウザの設定で Cookie を無効にします。\n\n6.本プライバシーポリシーの変更\n\n当社は、当社の慣行の変更を反映するため、またはその他の運用上、法律上、または規制上の理由により、本プライバシー ポリシーを随時更新することがあります。更新されたポリシーは、最新の改訂日とともに当社の Web サイトに掲載されます。\n\n7.お問い合わせ\n\nこのプライバシー ポリシーまたは当社のデータ慣行に関してご質問や懸念がある場合は、以下までお問い合わせください',],
        ];
        DB::table('contents')->insert($data);
    }
}
